name: Snyk Security Scan

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  snyk:
    runs-on: sonar   # your self-hosted runner label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Snyk installation
        run: snyk --version

      - name: Run Snyk security scan
        
        run: |
          cd backend
          
          snyk test > report.txt
          cat report.txt
